// Fetch-based client over the Anchor Quality Gate SaaS API.
//
// Hand-mirrors `schemas/openapi.yaml` for v1 alpha. v1.5 replaces this
// with a client generated by `openapi-typescript-codegen` so endpoint
// additions and schema changes don't need a manual edit here.

import { bytesToBase64, encryptForUpload, sha256Hex } from "./crypto";
import type {
  CreateRunRequest,
  DocumentRef,
  EncryptedUploadRequest,
  PublicKeyResponse,
  QualityReport,
  RunRef,
} from "./types";

export interface ClientOptions {
  baseUrl: string;
  apiKey: string;
  /** Used by tests; defaults to global fetch. */
  fetchImpl?: typeof fetch;
}

export class AnchorClient {
  constructor(private readonly opts: ClientOptions) {}

  private get fetchImpl(): typeof fetch {
    return this.opts.fetchImpl ?? fetch;
  }

  private headers(extra?: HeadersInit): Headers {
    const h = new Headers(extra);
    h.set("X-Anchor-API-Key", this.opts.apiKey);
    return h;
  }

  private url(path: string): string {
    return `${this.opts.baseUrl.replace(/\/$/, "")}${path}`;
  }

  async health(): Promise<{ status: string; version: string }> {
    const r = await this.fetchImpl(this.url("/v1/health"));
    if (!r.ok) throw new Error(`health failed: ${r.status}`);
    return r.json();
  }

  async getOrgPublicKey(): Promise<PublicKeyResponse> {
    const r = await this.fetchImpl(this.url("/v1/orgs/me/public-key"), {
      headers: this.headers(),
    });
    if (!r.ok) {
      throw new Error(`get public key failed: ${r.status} ${await r.text()}`);
    }
    return r.json();
  }

  async uploadDocument(file: File): Promise<DocumentRef> {
    const form = new FormData();
    form.append("file", file);
    const r = await this.fetchImpl(this.url("/v1/documents"), {
      method: "POST",
      body: form,
      headers: this.headers(),
    });
    if (!r.ok) {
      throw new Error(`upload failed: ${r.status} ${await r.text()}`);
    }
    return r.json();
  }

  /** Envelope-encrypt the bytes in-browser, then POST the encrypted payload. */
  async uploadDocumentEncrypted(
    plaintext: Uint8Array,
    publicKeyPem: string,
    filename?: string
  ): Promise<DocumentRef> {
    const payload = await encryptForUpload(plaintext, publicKeyPem);
    const body: EncryptedUploadRequest = {
      ciphertext_b64: bytesToBase64(payload.ciphertext),
      nonce_b64: bytesToBase64(payload.nonce),
      wrapped_dek_b64: bytesToBase64(payload.wrappedDek),
      sha256: payload.sha256Hex,
      original_filename: filename ?? null,
    };
    const r = await this.fetchImpl(this.url("/v1/documents/encrypted"), {
      method: "POST",
      headers: this.headers({ "Content-Type": "application/json" }),
      body: JSON.stringify(body),
    });
    if (!r.ok) {
      throw new Error(`encrypted upload failed: ${r.status} ${await r.text()}`);
    }
    return r.json();
  }

  async createRun(req: CreateRunRequest): Promise<RunRef> {
    const r = await this.fetchImpl(this.url("/v1/runs"), {
      method: "POST",
      headers: this.headers({ "Content-Type": "application/json" }),
      body: JSON.stringify(req),
    });
    if (!r.ok) {
      throw new Error(`create run failed: ${r.status} ${await r.text()}`);
    }
    return r.json();
  }

  async getRun(runId: string): Promise<QualityReport> {
    const r = await this.fetchImpl(this.url(`/v1/runs/${runId}`), {
      headers: this.headers(),
    });
    if (!r.ok) {
      throw new Error(`get run failed: ${r.status} ${await r.text()}`);
    }
    return r.json();
  }

  async downloadAnnotated(runId: string): Promise<Blob> {
    const r = await this.fetchImpl(
      this.url(`/v1/runs/${runId}/annotated.docx`),
      { headers: this.headers() }
    );
    if (!r.ok) {
      throw new Error(`download failed: ${r.status} ${await r.text()}`);
    }
    return r.blob();
  }
}

/** Convenience: hash bytes the same way the server expects. */
export { sha256Hex };
